### ISSUE TITLE
[AVM Question/Feedback]: compatibility issue

### ISSUE THREAD

**Issue by fwelk1337** [Azure/terraform-azurerm-avm-res-network-privatednszone#86]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Description

The version constraint "version = ">= 4.0, < 5.0" breaks compatibility with other verified modules that do not yet support version 4.0. Isn't it reasonable to expect that using the latest versions of all modules would prevent compatibility issues?

Example: 

│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/azurerm: no available releases match the given constraints >= 3.71.0, >= 3.114.0, >=  
│ 3.116.0, ~> 3.116.0, >= 4.0.0, < 4.0.0, < 5.0.0

**Comment by chianw** [comment]
@fwelk1337 thanks for the feedback. My understanding from @Azure/avm-core-team is that from v1 GA release of AVM modules, the minimum azurerm is 4.0 and minimum azapi is 2.0 so eventually all AVM modules will need to be at this release levels. 

@Azure/avm-core-team - please comment and advise.

**Comment by fwelk1337** [comment]
@chianw I might have been a bit too harsh, especially considering this isn't a stable version yet. Having to check the tags to find the right version constraint threw me off and made me question things a bit.

Anyway, thanks for the clarification. It does make sense for everything to be fully compatible at GA, but not now.
